// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: barrier.proto

package barrier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BarrierService_SendCompletion_FullMethodName = "/rpc.barrier.BarrierService/SendCompletion"
)

// BarrierServiceClient is the client API for BarrierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarrierServiceClient interface {
	SendCompletion(ctx context.Context, in *Completion, opts ...grpc.CallOption) (*CompletionResponse, error)
}

type barrierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBarrierServiceClient(cc grpc.ClientConnInterface) BarrierServiceClient {
	return &barrierServiceClient{cc}
}

func (c *barrierServiceClient) SendCompletion(ctx context.Context, in *Completion, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, BarrierService_SendCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarrierServiceServer is the server API for BarrierService service.
// All implementations must embed UnimplementedBarrierServiceServer
// for forward compatibility.
type BarrierServiceServer interface {
	SendCompletion(context.Context, *Completion) (*CompletionResponse, error)
	mustEmbedUnimplementedBarrierServiceServer()
}

// UnimplementedBarrierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBarrierServiceServer struct{}

func (UnimplementedBarrierServiceServer) SendCompletion(context.Context, *Completion) (*CompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCompletion not implemented")
}
func (UnimplementedBarrierServiceServer) mustEmbedUnimplementedBarrierServiceServer() {}
func (UnimplementedBarrierServiceServer) testEmbeddedByValue()                        {}

// UnsafeBarrierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarrierServiceServer will
// result in compilation errors.
type UnsafeBarrierServiceServer interface {
	mustEmbedUnimplementedBarrierServiceServer()
}

func RegisterBarrierServiceServer(s grpc.ServiceRegistrar, srv BarrierServiceServer) {
	// If the following call pancis, it indicates UnimplementedBarrierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BarrierService_ServiceDesc, srv)
}

func _BarrierService_SendCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Completion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrierServiceServer).SendCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarrierService_SendCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrierServiceServer).SendCompletion(ctx, req.(*Completion))
	}
	return interceptor(ctx, in, info, handler)
}

// BarrierService_ServiceDesc is the grpc.ServiceDesc for BarrierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BarrierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.barrier.BarrierService",
	HandlerType: (*BarrierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCompletion",
			Handler:    _BarrierService_SendCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "barrier.proto",
}
