// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: barrier.proto

package barrier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Completion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Completion) Reset() {
	*x = Completion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barrier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_barrier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_barrier_proto_rawDescGZIP(), []int{0}
}

type CompletionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barrier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barrier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_barrier_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_barrier_proto protoreflect.FileDescriptor

var file_barrier_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x72, 0x70, 0x63, 0x2e, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x22, 0x0c, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x12, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x5c, 0x0a, 0x0e, 0x42, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0e,
	0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x62, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x69, 0x74, 0x2e, 0x75,
	0x6e, 0x69, 0x72, 0x6f, 0x6d, 0x61, 0x32, 0x2e, 0x64, 0x69, 0x63, 0x69, 0x69, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_barrier_proto_rawDescOnce sync.Once
	file_barrier_proto_rawDescData = file_barrier_proto_rawDesc
)

func file_barrier_proto_rawDescGZIP() []byte {
	file_barrier_proto_rawDescOnce.Do(func() {
		file_barrier_proto_rawDescData = protoimpl.X.CompressGZIP(file_barrier_proto_rawDescData)
	})
	return file_barrier_proto_rawDescData
}

var file_barrier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_barrier_proto_goTypes = []any{
	(*Completion)(nil),         // 0: rpc.barrier.Completion
	(*CompletionResponse)(nil), // 1: rpc.barrier.CompletionResponse
}
var file_barrier_proto_depIdxs = []int32{
	0, // 0: rpc.barrier.BarrierService.SendCompletion:input_type -> rpc.barrier.Completion
	1, // 1: rpc.barrier.BarrierService.SendCompletion:output_type -> rpc.barrier.CompletionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_barrier_proto_init() }
func file_barrier_proto_init() {
	if File_barrier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_barrier_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Completion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barrier_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CompletionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barrier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_barrier_proto_goTypes,
		DependencyIndexes: file_barrier_proto_depIdxs,
		MessageInfos:      file_barrier_proto_msgTypes,
	}.Build()
	File_barrier_proto = out.File
	file_barrier_proto_rawDesc = nil
	file_barrier_proto_goTypes = nil
	file_barrier_proto_depIdxs = nil
}
