mappers_number: 3
reducers_number: 2
master:
  address: localhost
  port: 8000
workers:
  - address: localhost
    port: 9000
  - address: localhost
    port: 9001
  - address: localhost
    port: 9002
  - address: localhost
    port: 9003
  - address: localhost
    port: 9004